apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app
  namespace: crm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
      - name: crm-app
        image: 998718205665.dkr.ecr.eu-west-2.amazonaws.com/crm-app:1.0

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
